[package]
name = "snake"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.1"
rand = "0.8.5"
bevy-inspector-egui = "0.23.4"
bevy_asset_loader = { version = "0.20.0", features = ["2d"]}
console_error_panic_hook = "0.1"

